source ~/.zplug/init.zsh

PURE_GIT_PULL=0
eval "$(/opt/homebrew/bin/brew shellenv)"

zplug "mafredri/zsh-async"
zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
zplug "jimhester/per-directory-history"
zplug "zsh-users/zsh-history-substring-search", defer:3
zplug "chriskempson/base16-shell", from:github

# Check for uninstalled plugins.
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load

export CASE_SENSITIVE="true"

unsetopt correct_all
unsetopt correct

setopt auto_cd

#Allow rake commands to be run without escaping brackets
unsetopt nomatch

# Always reset terminal mode to original state after processes run
ttyctl -f

# Search history based on what's been typed with up and down arrow
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# Disk space is free, save history
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE

# Don't save duplicate commands in history
setopt histignoredups

export EDITOR=nvim

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export PATH=./bin:$HOME/.bin:/usr/local/bin:/usr/local/sbin:/opt/bin:$PATH
export PATH="$HOME/.local/bin:$PATH"

source $HOME/.zsh/aliases.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export SSH_AUTH_SOCK=/Users/andrew/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh

# Windsurf
export PATH="/Users/andrew/.codeium/windsurf/bin:$PATH"

eval "$(/opt/homebrew/bin/mise activate zsh)"
