export ZPLUG_HOME=$(brew --prefix)/opt/zplug
export ASDF_DIR=$(brew --prefix asdf)
source $ZPLUG_HOME/init.zsh

zplug "mafredri/zsh-async"
zplug "sindresorhus/pure", use:pure.zsh, as:theme
zplug "Tarrasch/zsh-autoenv"
zplug "jimhester/per-directory-history"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-history-substring-search", defer:3
zplug "chriskempson/base16-shell", defer:0
zplug "kiurchv/asdf.plugin.zsh", defer:2

# Check for uninstalled plugins.
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load

export CASE_SENSITIVE="true"

unsetopt correct_all
unsetopt correct

setopt auto_cd

#Allow rake commands to be run without escaping brackets
unsetopt nomatch

# Always reset terminal mode to original state after processes run
ttyctl -f

# Search history based on what's been typed with up and down arrow
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# Disk space is free, save history
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE

# Don't save duplicate commands in history
setopt histignoredups

export EDITOR=nvim

source $HOME/.zsh/aliases.zsh

export PATH=./bin:$HOME/.bin:/usr/local/bin:/usr/local/sbin:/opt/bin:$PATH

# LS colors, made with http://geoff.greer.fm/lscolors/
export LSCOLORS="exfxcxdxbxagadabagaxad"
export LS_COLORS='di=34;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=30;46:cd=0;43:su=30;41:sg=0;46:tw=30;40:ow=30;43:'
export CLICOLOR=1

# Disable Spring forever
export DISABLE_SPRING=true

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# Set up FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# This lists using git-ls-tree... not great for creating new files
# but very helpful for dotcom
# export FZF_DEFAULT_COMMAND='
#   git ls-tree -r --name-only HEAD ||
#   fd --type f --hidden --follow --exclude .git'
# export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

eval "$(nodenv init -)"
eval "$(rbenv init - zsh)"

export KITTY_CONFIG_DIRECTORY='~/.config/kitty/kitty.conf'
