export ZPLUG_HOME=~/.zplug
source ~/.zplug/init.zsh

zplug "mafredri/zsh-async"
zplug "sindresorhus/pure", use:pure.zsh, as:theme
zplug "Tarrasch/zsh-autoenv"
zplug "junegunn/fzf-bin", from:gh-r, as:command, rename-to:fzf
zplug "jimhester/per-directory-history"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2 # Should be loaded 2nd last.
zplug "zsh-users/zsh-history-substring-search", defer:3 # Should be loaded last.
zplug "mafredri/zsh-async", defer:0
zplug "sindresorhus/pure", use:pure.zsh, as:theme
zplug "chriskempson/base16-shell", defer:0

# Check for uninstalled plugins.
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load

export CASE_SENSITIVE="true"

unsetopt correct_all
unsetopt correct

setopt auto_cd

#Allow rake commands to be run without escaping brackets
unsetopt nomatch

# Always reset terminal mode to original state after processes run
ttyctl -f

# Search history based on what's been typed with up and down arrow
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# Disk space is free, save history
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE

# Don't save duplicate commands in history
setopt histignoredups

export EDITOR=nvim

source $HOME/.zsh/aliases.zsh

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# Initialize ASDF
[ -d $HOME/.asdf ]  && source $HOME/.asdf/asdf.sh
[ -d $HOME/.asdf ]  && source $HOME/.asdf/completions/asdf.bash

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
export PATH=./bin:$HOME/.bin:/usr/local/bin:/usr/local/sbin:/opt/bin:$PATH

# LS colors, made with http://geoff.greer.fm/lscolors/
export LSCOLORS="exfxcxdxbxagadabagaxad"
export LS_COLORS='di=34;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=30;46:cd=0;43:su=30;41:sg=0;46:tw=30;40:ow=30;43:'
export CLICOLOR=1

# Disable Spring forever
export DISABLE_SPRING=true
